# Generated by Django 3.2.12 on 2022-03-28 22:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('superhero_versus', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='superhero',
            name='combat',
            field=models.IntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='superhero',
            name='durability',
            field=models.IntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='superhero',
            name='intelligence',
            field=models.IntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='superhero',
            name='power',
            field=models.IntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='superhero',
            name='speed',
            field=models.IntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='superhero',
            name='strength',
            field=models.IntegerField(null=True),
        ),
    ]
